name: Run Workflow on Specific Branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to trigger workflow'
        required: true
        default: 'master'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch is correct
        run: |
          if [ "${{ github.event.inputs.branch }}" != "master" ]; then
            echo "This workflow can only be triggered for the 'master' branch.";
            exit 1;  # This stops the workflow if the branch is not 'master'
          fi

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run build
        run: |
          echo "Running build for the main branch"
